Repository ros2/system_tests, pull requests merged in 2018-06, with the labels that each got.

#271 Split ParameterVariant
  test_rclcpp/test/parameter_fixtures.hpp
  test_rclcpp/test/test_local_parameters.cpp
Labels: in review

#268 Add tests for command line remapping
  test_cli_remapping/CMakeLists.txt
  test_cli_remapping/package.xml
  test_cli_remapping/test/__init__.py
  test_cli_remapping/test/name_maker.cpp
  test_cli_remapping/test/name_maker.py
  test_cli_remapping/test/test_cli_remapping.py
Labels: in review

#273 migrate launch -> launch.legacy
  test_communication/test/test_publisher_subscriber.py.in
  test_communication/test/test_requester_replier.py.in
  test_rclcpp/test/test_executable_output.py.in
  test_rclcpp/test/test_two_executables.py.in
  test_security/test/test_secure_publisher_subscriber.py.in
Labels: in review

#272 Pass initial parameter values to node constructor
  test_rclcpp/test/test_multithreaded.cpp
Labels: in review

#275 use new launch legacy namespace
  test_cli_remapping/test/test_cli_remapping.py
Labels: in review

#276 Get parameters that aren't set should have type NOT_SET
  test_rclcpp/test/parameter_fixtures.hpp
Labels: bug

#280 comment out currently unused rclpy dependency
  test_security/package.xml
Labels: in review

#277 add test for set_parameters_atomically
  test_rclcpp/test/parameter_fixtures.hpp
  test_rclcpp/test/test_remote_parameters.cpp
Labels: in review

#283 use size_t
  test_communication/CMakeLists.txt
  test_communication/test/test_message_serialization.cpp
Labels: in progress

#281 Use debug python executable on windows
  test_cli/CMakeLists.txt
  test_cli/package.xml
  test_cli_remapping/CMakeLists.txt
  test_cli_remapping/package.xml
  test_communication/CMakeLists.txt
  test_communication/package.xml
Labels: bug, in review

#267 Expose cdr
  test_communication/CMakeLists.txt
  test_communication/test/test_message_serialization.cpp
  test_communication/test/test_publisher_subscriber_serialized.cpp
  test_rclcpp/test/test_multithreaded.cpp
  test_rclcpp/test/test_spin.cpp
  test_rclcpp/test/test_subscription.cpp
Labels: in progress

#284 only test serialization on fastrtps and connext
  test_communication/CMakeLists.txt
Labels: in review
