Repository ros2/system_tests, pull requests merged in 2018-11, with the labels that each got.

#306 use new error handling API from rcutils
  test_communication/test/test_messages_c.cpp
  test_security/test/test_invalid_secure_node_creation_c.cpp
Labels: enhancement, in review

#307 rename dynamic array to sequence
  test_communication/test/test_message_serialization.cpp
  test_communication/test/test_messages_c.cpp
Labels: in review

#308 Adjusting namespace for security tests
  test_security/test/test_secure_publisher_subscriber.py.in
Labels: in review

#311 Update rcl_wait_set_add_guard_condition() call
  test_communication/test/test_messages_c.cpp
Labels: in review

#312 add new fixtures
  test_communication/test/test_publisher.cpp
  test_communication/test/test_publisher_subscriber.cpp
  test_communication/test/test_subscriber.cpp
Labels: in progress

#314 Add test for waitable
  test_rclcpp/CMakeLists.txt
  test_rclcpp/test/test_waitable.cpp
Labels: in review

#313 refactor to support init options and context
  test_communication/CMakeLists.txt
  test_communication/package.xml
  test_communication/test/test_messages_c.cpp
  test_communication/test/test_publisher_subscriber.cpp
  test_rclcpp/CMakeLists.txt
  test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
  test_rclcpp/test/test_client_scope_client.cpp
  test_rclcpp/test/test_client_scope_consistency_client.cpp
  test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
  test_rclcpp/test/test_executor.cpp
  test_rclcpp/test/test_local_parameters.cpp
  test_rclcpp/test/test_multiple_service_calls.cpp
  test_rclcpp/test/test_multithreaded.cpp
  test_rclcpp/test/test_publisher.cpp
  test_rclcpp/test/test_remote_parameters.cpp
  test_rclcpp/test/test_services_client.cpp
  test_rclcpp/test/test_services_in_constructor.cpp
  test_rclcpp/test/test_signal_handler_before_shutdown__expected_output.txt
  test_rclcpp/test/test_spin.cpp
  test_rclcpp/test/test_subscription.cpp
  test_rclcpp/test/test_timer.cpp
  test_rclcpp/test/test_waitable.cpp
  test_security/test/test_invalid_secure_node_creation_c.cpp
Labels: enhancement, in review
