Repository ros2/system_tests, pull requests merged in 2019-05, with the labels that each got.

#350 Use new interface definitions
  test_communication/msg/FieldsWithSameType.msg
  test_communication/test/test_message_serialization.cpp
  test_communication/test/test_messages_c.cpp
  test_communication/test/test_publisher.cpp
  test_communication/test/test_publisher_subscriber.cpp
  test_communication/test/test_publisher_subscriber_serialized.cpp
  test_communication/test/test_replier.cpp
  test_communication/test/test_requester.cpp
  test_communication/test/test_subscriber.cpp
  test_security/test/test_secure_publisher.cpp
  test_security/test/test_secure_subscriber.cpp
Labels: in review

#345 [WIP] Modify get_node_names to return fully qualified names
  test_rclcpp/test/node_check_names.cpp
  test_rclcpp/test/node_name_list.cpp
Labels: in review

#352 API updates for RMW preallocation work.
  test_communication/test/test_messages_c.cpp
Labels: in progress

#353 add WString tests
  test_communication/test/test_publisher.cpp
  test_communication/test/test_publisher_subscriber.cpp
  test_communication/test/test_subscriber.cpp
Labels: in review

#349 Fix call to rcl_wait_set_init() after API changed
  test_communication/test/test_messages_c.cpp
Labels: in review

#354 skip cross vendor testing of OpenSplice for WStrings
  test_communication/CMakeLists.txt
Labels: bug, in review

#355 Fix issues with C messages test
  test_communication/test/test_messages_c.cpp
Labels: bug, in review

#356 Using new parameter API: allowing undeclared parameters.
  test_cli/test/initial_params.py
  test_cli/test/test_params_yaml.py
Labels: in progress

#357 Delete unnecessary usage of target_include_directories and target_link_libraries with gtest macros
  test_rclcpp/CMakeLists.txt
Labels: in review

#348 Corrected publish calls with shared_ptr signature
  test_communication/test/test_publisher.cpp
  test_communication/test/test_publisher_subscriber.cpp
  test_communication/test/test_publisher_subscriber_serialized.cpp
  test_communication/test/test_subscription_valid_data.cpp
  test_rclcpp/test/pub_sub_fixtures.hpp
  test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
  test_rclcpp/test/test_intra_process.cpp
  test_rclcpp/test/test_multithreaded.cpp
  test_rclcpp/test/test_publisher.cpp
  test_rclcpp/test/test_repeated_publisher_subscriber.cpp
  test_rclcpp/test/test_spin.cpp
  test_rclcpp/test/test_subscription.cpp
  test_security/test/test_secure_publisher.cpp
Labels: in review

#358 Declaring initial parameters.
  test_cli/test/initial_params.py
  test_cli/test/test_params_yaml.py
Labels: in review

#361 changes to avoid deprecated API's
  test_cli_remapping/test/name_maker.cpp
  test_communication/test/test_publisher.cpp
  test_communication/test/test_publisher_subscriber.cpp
  test_communication/test/test_publisher_subscriber_serialized.cpp
  test_communication/test/test_subscriber.cpp
  test_communication/test/test_subscription_valid_data.cpp
  test_rclcpp/test/pub_sub_fixtures.hpp
  test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
  test_rclcpp/test/test_executor.cpp
  test_rclcpp/test/test_intra_process.cpp
  test_rclcpp/test/test_multithreaded.cpp
  test_rclcpp/test/test_publisher.cpp
  test_rclcpp/test/test_repeated_publisher_subscriber.cpp
  test_rclcpp/test/test_spin.cpp
  test_rclcpp/test/test_subscription.cpp
  test_rclcpp/test/test_timeout_subscriber.cpp
  test_security/test/test_secure_publisher.cpp
  test_security/test/test_secure_subscriber.cpp
Labels: in progress

#363 Make test_subscriber_cpp always fail gracefully.
  test_communication/test/test_subscriber.cpp
Labels: in review

#364 Fix deprecation warnings
  test_cli_remapping/test/name_maker.py
  test_communication/test/publisher_py.py
  test_communication/test/subscriber_py.py
Labels: in progress

#367 Handle launch_testing assertExitCodes correctly
  test_communication/test/test_action_client_server.py.in
  test_communication/test/test_publisher_subscriber.py.in
  test_communication/test/test_requester_replier.py.in
  test_rclcpp/test/test_n_nodes.py.in
  test_rclcpp/test/test_two_executables.py.in
  test_security/test/test_secure_publisher_subscriber.py.in
Labels: in review

#366 Improve tests for parameters
  test_rclcpp/test/parameter_fixtures.hpp
  test_rclcpp/test/test_local_parameters.cpp
  test_rclcpp/test/test_parameters_server.cpp
  test_rclcpp/test/test_remote_parameters.cpp
  test_rclcpp/test/test_two_executables.py.in
Labels: in review

#368 Fix memory leaks in test_communication tests
  test_communication/test/test_message_serialization.cpp
  test_communication/test/test_messages_c.cpp
Labels: in progress

#369 disable long term flaky test test_params_yaml
  test_cli/CMakeLists.txt
Labels: in review

#347 QoS System Tests
  test_quality_of_service/CMakeLists.txt
  test_quality_of_service/include/test_quality_of_service/qos_test_node.hpp
  test_quality_of_service/include/test_quality_of_service/qos_test_publisher.hpp
  test_quality_of_service/include/test_quality_of_service/qos_test_subscriber.hpp
  test_quality_of_service/include/test_quality_of_service/qos_utilities.hpp
  test_quality_of_service/package.xml
  test_quality_of_service/test/qos_test_node.cpp
  test_quality_of_service/test/qos_test_publisher.cpp
  test_quality_of_service/test/qos_test_subscriber.cpp
  test_quality_of_service/test/qos_utilities.cpp
  test_quality_of_service/test/test_deadline.cpp
  test_quality_of_service/test/test_lifespan.cpp
  test_quality_of_service/test/test_liveliness.cpp
Labels: in review

#370 update to use new parameter option names
  test_cli/test/initial_params.cpp
  test_cli/test/initial_params.py
  test_cli/test/test_params_yaml.py
Labels: in review
