Repository ros2/system_tests, pull requests merged in 2019-04, with the labels that each got.

#343 Change use of deprecated rclcpp APIs
  test_rclcpp/test/test_multithreaded.cpp
Labels: in progress

#344 Update to be compatible with new rmw_qos_profile_t
  test_rclcpp/test/test_client_scope_consistency_client.cpp
  test_rclcpp/test/test_client_scope_consistency_server.cpp
Labels: in review

#342 Rename action state transitions
  test_communication/test/action_server_py.py
  test_communication/test/test_action_server.cpp
Labels: in review

#278 Read only parameters
  test_cli/test/initial_params.cpp
  test_rclcpp/test/parameter_fixtures.hpp
  test_rclcpp/test/test_local_parameters.cpp
  test_rclcpp/test/test_parameters_server.cpp
Labels: enhancement, in progress

#346 Update call to async_send_goal
  test_communication/test/test_action_client.cpp
Labels: in review

#340 Migrate launch tests to new launch_testing features & API
  test_cli_remapping/CMakeLists.txt
  test_cli_remapping/package.xml
  test_cli_remapping/test/test_cli_remapping.py
  test_communication/CMakeLists.txt
  test_communication/package.xml
  test_communication/test/test_action_client_server.py.in
  test_communication/test/test_publisher_subscriber.py.in
  test_communication/test/test_requester_replier.py.in
  test_rclcpp/CMakeLists.txt
  test_rclcpp/package.xml
  test_rclcpp/test/test_executable_output.py.in
  test_rclcpp/test/test_n_nodes.py.in
  test_rclcpp/test/test_two_executables.py.in
  test_security/CMakeLists.txt
  test_security/package.xml
  test_security/test/test_secure_publisher_subscriber.py.in
Labels: in review
