Repository ros2/system_tests, pull requests merged in 2019-03, with the labels that each got.

#334 Add launch along with launch_testing as test dependencies.
  test_cli_remapping/package.xml
  test_communication/package.xml
  test_rclcpp/package.xml
  test_security/package.xml
Labels: in review

#333 Add communication tests for Python Actions
  test_communication/CMakeLists.txt
  test_communication/test/action_client_py.py
  test_communication/test/action_server_py.py
Labels: in review

#335 [Crystal patch 3 backport] Add test for test_msgs/NestedMessage.action (#330)
  test_communication/test/test_action_client.cpp
  test_communication/test/test_action_server.cpp
Labels: in progress

#315 update char type mapping, update to use separated action types
  test_communication/test/action_client_py.py
  test_communication/test/test_action_client.cpp
  test_communication/test/test_action_server.cpp
  test_communication/test/test_messages_c.cpp
Labels: in review

#336 refactor test generation
  test_communication/CMakeLists.txt
  test_communication/test/test_action_client_server.py.in
  test_communication/test/test_publisher_subscriber.py.in
  test_communication/test/test_requester_replier.py.in
Labels: enhancement, in review

#337 Add communication tests for Python Actions (#333)
  test_communication/CMakeLists.txt
  test_communication/test/action_client_py.py
  test_communication/test/action_server_py.py
Labels: in review

#338 Prepare 0.6.1
  test_cli/package.xml
  test_cli_remapping/package.xml
  test_communication/package.xml
  test_rclcpp/package.xml
  test_security/package.xml
Labels: in review

#339 Using ament_target_dependencies where possible
  test_communication/CMakeLists.txt
Labels: in review

#341 fixes a failing test introduced by the switch to array.array
  test_cli/test/test_params_yaml.py
Labels: in review
